Groupbranch Merge BSAPP 825, 826, 828, 830, 831
exxcellent/swt2-bsa-backend pull request #195
Opened 2021-03-25 15:10 UTC by kayaok

BSAPP-825 equals methode in DsbMannschaftService.java
BSAPP-826: equals-MethodeVereineService.java
BSAPP-828: Bugfix in Datei VeranstaltungService.java
BSAPP-830: equals-Methode MannschaftsMitgliedService.java
BSAPP-831: equals-Methode statt == MatchService.java

2021-03-25 15:22 UTC, carawendt requested changes
Kommentare und Test fehlen noch

2021-04-06 13:20 UTC, MarioaAk commented
Ich habe alle Code-Smells auf fixed gesetzt, welche das Problem mit den Request Settings hatten

2021-04-07 09:15 UTC, Patrick762 commented on bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/mannschaftsmitglied/service/MannschaftsMitgliedService.java
>              throw new NoPermissionException();
this might allow invalid parameters

2021-04-07 09:18 UTC, Patrick762 commented on bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/match/service/MatchService.java
> +                //the required Permission (if the permission is specify
maybe they meant "specific"

2021-04-07 09:29 UTC, Patrick762 reviewed
OK

2021-04-07 09:35 UTC, Patrick762 approved these changes

2021-04-08 14:17 UTC, carawendt approved these changes

2021-04-15 11:02 UTC, MichaelSVF commented on bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/match/service/MatchService.java
> +                Long userId = jwtTokenProvider.getUserId(jwt);
nach meinem Wissen funktioniert der Aufruf des jwtTokenProvider zum ermitteln der UserID nicht - habt ihr das gründlich getestet?

2021-04-15 11:03 UTC, MichaelSVF commented on bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/veranstaltung/service/VeranstaltungService.java
> +                Long userId = jwtTokenProvider.getUserId(jwt);
s.o.

2021-04-15 11:03 UTC, MichaelSVF commented on bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/vereine/service/VereineService.java
> +                Long userId = jwtTokenProvider.getUserId(jwt);
s.o.

2021-04-30 14:45 UTC, merged